In [21]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import pandas as pd
import numpy  as np

In [6]:
d=load_iris()

In [15]:
l=cross_val_score(LogisticRegression(),d.data,d.target)
l

array([0.96078431, 0.92156863, 0.95833333])

In [17]:
np.average(l)

0.9468954248366014

In [18]:
r=cross_val_score( RandomForestClassifier(),d.data,d.target)
r

array([0.98039216, 0.92156863, 0.97916667])

In [19]:
np.average(r)

0.960375816993464

In [22]:
r1=cross_val_score(SVC(),d.data,d.target)
r1

array([0.98039216, 0.96078431, 0.97916667])

In [23]:
np.average(r1)

0.9734477124183006